#!/usr/bin/env bash
# Updates an existing Player Pulse on-premise installation to a specific bundle version.
# Usage: ./update.sh 1.4.2
#        ./update.sh --rollback
#        ./update.sh --check
#
# Downloads that release's docker-compose.on-premise.yml (the version manifest for the bundle),
# replaces the local one, pulls new images, and restarts. Migrations run automatically
# on startup via the migrations service already defined in the compose file.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

REPO="Moai-Team-LLC/player-pulse-on-premise"
COMPOSE_FILE="docker-compose.on-premise.yml"
BACKUP_FILE="docker-compose.on-premise.yml.bak"
VERSION_HISTORY_FILE=".version_history"

installed_version() {
  local image
  image="$(docker compose -f "$COMPOSE_FILE" ps --format '{{.Image}}' api 2>/dev/null || true)"
  [ -n "$image" ] || return
  echo "${image##*:}"
}

# Bootstrap history with whatever's currently deployed, the first time this
# script ever tracks versions — otherwise the very first --rollback after the
# very first update would have nothing to fall back to.
if [ ! -f "$VERSION_HISTORY_FILE" ]; then
  bootstrap="$(installed_version)"
  [ -n "$bootstrap" ] && echo "$bootstrap" > "$VERSION_HISTORY_FILE"
fi

# ── --check: read-only, reports how far behind the latest release, changes nothing ──
if [ "${1:-}" = "--check" ]; then
  current="$(installed_version)"
  if [ -z "$current" ]; then
    echo "Could not determine the currently installed version — is the 'api' container running?" >&2
    exit 1
  fi
  echo "Currently installed: ${current}"

  latest="$(curl -sf "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null | grep '"tag_name"' | head -n1 | sed -E 's/.*"tag_name": *"v?([^"]+)".*/\1/')"
  if [ -z "$latest" ]; then
    echo "Could not reach GitHub to check the latest release." >&2
    exit 1
  fi

  if [ "$latest" = "$current" ]; then
    echo "You're up to date."
  else
    echo "A newer version is available: ${latest}"
    echo "Run: ./update.sh ${latest}"
  fi
  exit 0
fi

# ── --rollback: pop the current version, redeploy whatever's now on top ────
ROLLBACK=false
if [ "${1:-}" = "--rollback" ]; then
  ROLLBACK=true
  entry_count="$(wc -l < "$VERSION_HISTORY_FILE" | tr -d ' ')"
  if [ "$entry_count" -lt 2 ]; then
    echo "No previous version recorded to roll back to." >&2
    exit 1
  fi
  VERSION="$(tail -n2 "$VERSION_HISTORY_FILE" | head -n1)"
  echo "Rolling back to the last known-good version: ${VERSION}"
else
  VERSION="${1:-}"
fi

if [ -z "$VERSION" ]; then
  echo "Usage: ./update.sh <version>" >&2
  echo "       ./update.sh --rollback   (go back to the last known-good version)" >&2
  echo "       ./update.sh --check      (see if a newer version is available)" >&2
  echo "Example: ./update.sh 1.4.2" >&2
  exit 1
fi

if [ ! -f ".env" ]; then
  echo ".env not found — this doesn't look like an existing installation." >&2
  echo "Run ./install.sh first to set up a new installation." >&2
  exit 1
fi

TAG="v${VERSION}"
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${TAG}/${COMPOSE_FILE}"

echo "Fetching compose file for bundle ${VERSION}..."
TMP_FILE="$(mktemp)"

if ! curl -sfL "$DOWNLOAD_URL" -o "$TMP_FILE"; then
  echo "Failed to download ${COMPOSE_FILE} for release ${TAG}." >&2
  echo "Check that ${TAG} exists at: https://github.com/${REPO}/releases" >&2
  rm -f "$TMP_FILE"
  exit 1
fi

echo "Downloaded successfully."

if [ -f "$COMPOSE_FILE" ]; then
  cp "$COMPOSE_FILE" "$BACKUP_FILE"
  echo "Backed up current compose file to ${BACKUP_FILE}."
fi

mv "$TMP_FILE" "$COMPOSE_FILE"
echo "Replaced ${COMPOSE_FILE} with bundle ${VERSION}."
echo

# ── Sync new required config into .env ──────────────────────────────────────
# Bundles can introduce new env vars (e.g. a new adapter). Fetch that bundle's
# .env.example and add anything missing from the local .env: vars with a literal
# default get that default, vars marked "generated by install.sh" get a fresh
# random value, vars marked "optional" get added blank, anything else needs a
# real value from the client — we stop and ask rather than start containers
# that are guaranteed to crash-loop.
echo "Checking for new config introduced in bundle ${VERSION}..."
ENV_EXAMPLE_URL="https://raw.githubusercontent.com/${REPO}/${TAG}/.env.example"
ENV_EXAMPLE_TMP="$(mktemp)"

if curl -sfL "$ENV_EXAMPLE_URL" -o "$ENV_EXAMPLE_TMP"; then
  missing_manual=()
  added=()

  while IFS= read -r line; do
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^([A-Z0-9_]+)= ]] || continue
    key="${BASH_REMATCH[1]}"

    grep -q "^${key}=" ".env" 2>/dev/null && continue

    rest="${line#*=}"
    value="$(echo -n "${rest%%#*}" | sed -e 's/[[:space:]]*$//')"

    if [[ "$rest" == *"generated by install.sh"* ]]; then
      echo "${key}=$(openssl rand -hex 32)" >> ".env"
      added+=("$key (generated)")
    elif [[ -n "$value" ]]; then
      echo "${key}=${value}" >> ".env"
      added+=("$key (default: ${value})")
    elif [[ "$rest" == *"optional"* ]]; then
      echo "${key}=" >> ".env"
      added+=("$key (optional, left blank)")
    else
      missing_manual+=("$key")
    fi
  done < "$ENV_EXAMPLE_TMP"
  rm -f "$ENV_EXAMPLE_TMP"

  if [ ${#added[@]} -gt 0 ]; then
    echo "Added new config to .env:"
    for k in "${added[@]}"; do
      echo "  - $k"
    done
  else
    echo "No new config needed."
  fi

  if [ ${#missing_manual[@]} -gt 0 ]; then
    echo
    echo "Bundle ${VERSION} requires new config you need to provide manually:" >&2
    for k in "${missing_manual[@]}"; do
      echo "  - $k" >&2
    done
    echo
    echo "Add these to .env, then re-run: ./update.sh ${VERSION}" >&2
    exit 1
  fi
else
  echo "Warning: could not fetch .env.example for ${TAG} — skipping config sync." >&2
  echo "If containers fail to start, check the release notes for new required .env variables." >&2
  rm -f "$ENV_EXAMPLE_TMP"
fi
echo

# Include a private adapter override file automatically if one exists in this directory.
COMPOSE_ARGS=(-f "$COMPOSE_FILE")
OVERRIDE_FILE="$(find . -maxdepth 1 -name '*.override.yml' -print -quit)"
if [ -n "$OVERRIDE_FILE" ]; then
  echo "Found private adapter override: ${OVERRIDE_FILE}"
  COMPOSE_ARGS+=(-f "$OVERRIDE_FILE")
fi

echo "Pulling new images..."
docker compose "${COMPOSE_ARGS[@]}" pull

echo "Restarting services..."
docker compose "${COMPOSE_ARGS[@]}" up -d

# ── Health check ──────────────────────────────────────────────────────────────
echo "Waiting for API to become healthy..."
API_PORT_VALUE="$(grep '^API_PORT=' .env | cut -d= -f2)"

HEALTHY=false
for _ in $(seq 1 30); do
  if curl -sf "http://localhost:${API_PORT_VALUE}/api/v1/healthcheck" >/dev/null 2>&1; then
    HEALTHY=true
    break
  fi
  sleep 2
done

echo
if [ "$HEALTHY" = true ]; then
  if [ "$ROLLBACK" = false ]; then
    echo "$VERSION" >> "$VERSION_HISTORY_FILE"
  else
    sed -i.bak '$d' "$VERSION_HISTORY_FILE" && rm -f "${VERSION_HISTORY_FILE}.bak"
  fi
  echo "Update to ${VERSION} complete. API is healthy."
  echo "See what's new: https://github.com/${REPO}/releases/tag/${TAG}"
else
  echo "Update to ${VERSION} finished, but API did not become healthy in time." >&2
  echo "Check logs with: docker compose ${COMPOSE_ARGS[*]} logs api" >&2
  echo "To roll back: mv ${BACKUP_FILE} ${COMPOSE_FILE} && docker compose ${COMPOSE_ARGS[*]} up -d" >&2
  exit 1
fi